blog/urls.py
from django.contrib import admin
from django.urls import path


from . import views

app_name = "blog"

urlpatterns = [
    # 전체 게시물 확인
    path("", views.PostList.as_view(), name="list"),
    # 상세 페이지 조회
    path("<int:post_id>/", views.PostDetail.as_view(), name="detail"),
    # 게시글 작성
    path("create/", views.PostWrite.as_view(), name="write"),
    # 게시글 수정
    path("edit/<int:post_id>/", views.PostEdit.as_view(), name="edit"),
    # 게시글 삭제
    path("delete/<int:post_id>/", views.PostDelete.as_view(), name="delete"),
    # 게시글 검색1
    # path("search/", views.PostSearchQuery.as_view(), name="search-query"),
    # 게시글 검색
    path("posts/", views.PostSearch.as_view(), name="post-search"),
    # 카테고리 종류로 검색
    path("category/<str:cat>/", views.CategorySearch.as_view(), name="search-category"),
    # 코멘트 작성
    path("detail/<int:post_id>/comment/write/", views.CommentWrite.as_view(), name="cm-write"),
    # 코멘트 삭제
    path("detail/comment/<int:cm_id>/delete/", views.CommentDelete.as_view(), name="cm-delete"),
    ## 대댓글 작성
    path("detail/<int:post_id>/comment/<int:cm_id>/replywrite/", views.ReCommentWrite.as_view(), name="rcm-write"),
    ## 대댓글 삭제
    path("detail/<int:post_id>/comment/replydelete/<int:rcm_id>/", views.ReCommentDelete.as_view(), name="rcm-delete"),
    
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexMain.as_view()),
    path("blog/", include("blog.urls")),
    path("user/", include("user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.page_not_found'

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

## auth를 확장된 모델을 가져오게 됩니다.
User = get_user_model()

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey("Category", null=True, blank=True, on_delete=models.SET_NULL)
    hits = models.PositiveIntegerField(default=0, verbose_name='조회수')
    image = models.ImageField(upload_to="images/", null=True, blank=True)

    def __str__(self):
        return f"[{self.pk}] {self.title} :: {self.author} - {self.created_at}"


class Comment(models.Model):
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)    


class ReComment(models.Model):
    comment = models.ForeignKey("Comment", on_delete=models.CASCADE)
    content = models.TextField(max_length=500)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)    


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("blog:search-category", kwargs={"cat": self.name})
    

blog/forms.py
from django import forms
from .models import Post, Comment, ReComment, Category


class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'category']
        widgets ={
            'title':forms.TextInput(attrs={
                'class': 'form-control'
                }),
            'category':forms.Select(attrs={
                'class': 'form-control'
                }),
            'content':forms.Textarea(attrs={
                'class': 'form-control',
                'style': 'width:100%;'
                }),
            'image':forms.FileInput(attrs={
                'class': 'form-control'
                })
            }


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'style' : 'height:4em',
                'class':'form-control'
                })
        }


class ReCommentForm(forms.ModelForm):
    
    class Meta:
        model = ReComment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'style' : 'height:4em',
                'class':'form-control'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
# from django.db.models import Q

# auth의 mixin 기능
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from datetime import date, datetime, timedelta

from .models import Post, Comment, Category, ReComment
from .forms import PostForm, CommentForm, ReCommentForm



class PostList(View):
    def get(self, request):
        post_list = Post.objects.all().order_by('-created_at')
        query_pagenum = request.GET.get('page')
        
        posts_num = len(post_list)
        categories = Category.objects.all()
        cat_null_posts = Post.objects.filter(category__isnull=True)
        
        paginator = Paginator(post_list, 4)
        
        # 페이지 수 에러처리.
        try:
            posts = paginator.get_page(query_pagenum)
        except PageNotAnInteger:
            query_pagenum = 1
            posts = paginator.get_page(query_pagenum)
        except EmptyPage:
            query_pagenum = paginator.num_pages
            posts = paginator.get_page(query_pagenum)
            
        total_page = paginator.num_pages
        context = {
            "post_list": post_list,
            "posts_num": posts_num,
            "categories": categories,
            "posts" : posts,
            "cat_null_posts": cat_null_posts,
            "paginator": paginator,
        }
        # return render(request, "blog/post_list.html", context=context)
        return render(request, "blog/post_list.html", context=context)


class PostDetail(View):
    def get(self, request, post_id):        
        # 404발생 즉시 중단되고 404를 출력해줌
        post = get_object_or_404(Post, pk= post_id)
        comments = Comment.objects.filter(post=post).order_by("-created_at")
        comment_form = CommentForm()
        recomment_form = ReCommentForm()
        context = {
            "post": post,
            "comments": comments,
            "comment_form": comment_form,
            "recomment_form": recomment_form
        }
        
        # HttpResponse 생성
        response = render(request, "blog/post_detail.html", context=context)
        
        # 쿠키 만료기간 설정을 위한 셋
        expire_date, now = datetime.now(), datetime.now()
        expire_date += timedelta(hours=1)
        expire_date -= now
        max_age = expire_date.total_seconds()

        # 클라이언트의 쿠키 얻기
        cookie_value = request.COOKIES.get('hitpost', '_')
        
        if f'_{post_id}_' not in cookie_value:
            cookie_value += f'{post_id}_'
            # python에서 쿠키생성 set_cookie(쿠키이름, 값, 만료기간, js접근불가능)
            # 쿠키가 없으면 생성, 있으면 추가하는 메서드
            response.set_cookie('hitpost', value=cookie_value, max_age=max_age, httponly=True)
            post.hits +=1
            post.save()
        
        return response


class PostWrite(LoginRequiredMixin, View):
    def get(self, request):
        form = PostForm()
        context = {
            "form":form,
        }
        return render(request, "blog/post_write.html", context=context)

    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            if request.FILES:
                print(request.FILES['image'])
                post.image = request.FILES['image']
            post.save()
            return redirect('blog:list')
        
        # form.add_error(None, '폼이 유효하지 않습니다.') # 에러 전달도 해줘야함
        return redirect('blog:write')


class PostEdit(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        # print(post.image)
        form = PostForm(initial={'title':post.title, 'content':post.content, 'category': post.category, 'author': post.author, 'image': post.image })
        
        context = {
            'post': post,
            'form': form
        }
        return render(request, "blog/post_edit.html", context=context)
    
    def post(self, request, post_id):
        post =Post.objects.get(pk=post_id)
        checked = request.POST.getlist("cancel") # [] or ['1']
        if post.author == request.user or request.user.is_superuser:
            form = PostForm(request.POST, request.FILES)

            if form.is_valid():
                post.title = form.cleaned_data["title"]
                post.content = form.cleaned_data["content"]
                post.category = form.cleaned_data["category"]
                post.image = request.POST['originimage'] # form안 input들의 name이 key로, value는 value로 들어감.
                
                if request.FILES :
                    post.image = request.FILES['image']
                
                if bool(checked) :
                    post.image = None # None 들어가는거 맞겠지?
                    
                post.save()
                return redirect('blog:detail', post_id=post_id)
            
            form.add_error(None, '폼이 유효하지 않습니다.')
            context = {
                'form': form,
                'post': post
            }
            return render(request, 'blog/post_edit.html', context=context)
        
        return redirect('blog:edit', post_id=post_id)


class PostDelete(LoginRequiredMixin, View):
    def post(self, request, post_id):
        post = Post.objects.get(pk=post_id)
        post.delete()
        return redirect('blog:list')


# search url 규칙을 맞추기 위해 요청만 보냄.
## TODO - 거쳐가지 않고 한번에 가도록 수정해야 함.
# class PostSearchQuery(View):
#     def get(self, request):
#         print(request)
#         print(request.GET)
#         cat = request.GET.get('cat')
#         if cat == '':
#             cat = 'All'
#             return redirect('blog:list')
#         print(cat)
#         return redirect('blog:search', cat=cat)


class PostSearch(View):
    # TODO 추후 여러개, 제목/내용/작성자 에 대한 검색, 대소문자 고려해보기
    
    def get(self, request):
        qp = request.GET.get('search', None)
        query_pagenum = request.GET.get('page', None)
        
        if qp == None:
            return redirect('blog:list')
        else:
            search_result = Post.objects.filter(title__icontains=qp)
            print(search_result)
            
            posts_num = len(search_result)
            categories = Category.objects.all()
            cat_null_posts = Post.objects.filter(category__isnull=True)
            
            paginator = Paginator(search_result, 4)
            # 페이지 수 에러처리.
            try:
                posts = paginator.get_page(query_pagenum)
            except PageNotAnInteger:
                query_pagenum = 1
                posts = paginator.get_page(query_pagenum)
            except EmptyPage:
                query_pagenum = paginator.num_pages
                posts = paginator.get_page(query_pagenum)
                
            total_page = paginator.num_pages
            context = {
                "post_list": search_result,
                "posts_num": posts_num,
                "categories": categories,
                "posts" : posts,
                "cat_null_posts": cat_null_posts,
                "paginator": paginator,
                "qp": qp,
            }

            return render(request, "blog/post_list.html", context=context)
    


class CategorySearch(View):
    def get(self, request, cat):
        ## 단일 카테고리에 일치하는 것만 검색
        posts_num = Post.objects.count()
        categories = Category.objects.all()
        cat_null_posts = Post.objects.filter(category__isnull=True)
        if cat == "None":
            post_list =  Post.objects.filter(category=None).order_by('-created_at')
        else:
            category = Category.objects.filter(name=cat)
            
            if category:
                print("here!")
                post_list =  Post.objects.filter(category=category[0]).order_by('-created_at')
            else:
                post_list = None

        query_pagenum = request.GET.get('page', None)
        
        paginator = Paginator(post_list, 4)
        
        # 페이지 수 에러처리.
        try:
            posts = paginator.get_page(query_pagenum)
        except PageNotAnInteger:
            query_pagenum = 1
            posts = paginator.get_page(query_pagenum)
        except EmptyPage:
            query_pagenum = paginator.num_pages
            posts = paginator.get_page(query_pagenum)
        
        # print(posts, posts.number, len(posts))
        # print(query_pagenum, paginator.page_range, post_list, len(post_list))
        
        context = {
            "posts" : posts,
            "posts_num": posts_num,
            "searchtag": cat,
            "categories": categories,
            "cat_null_posts": cat_null_posts,
            "paginator": paginator,
        }
        return render(request, 'blog/post_list.html', context=context)
    

class CommentWrite(LoginRequiredMixin, View):
    def post(self, request, post_id):
        form = CommentForm(request.POST)
        post = get_object_or_404(Post, pk=post_id)
        
        if form.is_valid():
            content = form.cleaned_data['content']
            author = request.user
            
            comment = Comment.objects.create(post=post, content=content, author=author)
            
            return redirect("blog:detail", post_id=post_id)
        
        form.add_error('content','폼이 유효하지 않습니다.')
        context = {
            'post': post,
            'comments': post.comment_set.all(),
            'comment_form': form
        }
        return render(request, "blog/post_detailhtml", context=context)


class CommentDelete(LoginRequiredMixin, View):
    def post(self, request, cm_id):
        comment = get_object_or_404(Comment, pk=cm_id)
        print(comment)
        postid = comment.post.id
        comment.delete()
        return redirect('blog:detail', post_id=postid)


### 대댓글
class ReCommentWrite(LoginRequiredMixin, View):
    def post(self, request, post_id, cm_id):

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <main class="container">
        <h2>{{ post.title }} </h2> 
        <p class="badge rounded-pill text-bg-primary">{% if post.category == None %} Uncategorized {% else %}{{ post.category }}{%endif%}</p>
        {% if user == post.author or user.is_superuser %}
        <div class="d-grid gap-2 d-flex justify-content-end">
            <a href="{% url 'blog:edit' post_id=post.pk %}" class="btn btn-warning">글수정</a>
            <form action="{% url 'blog:delete' post_id=post.pk%}" method="post">
                {% csrf_token %}
                <input type="submit" value="글삭제" class="btn btn-warning">
            </form>
        </div>
        {% endif %}
        
        <hr>
        <div class="card" style="width: 100%;">
            <!-- <img src="..." class="card-img-top" alt="..."> -->
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-warning" style="--bs-bg-opacity: .1;">
                        <div class="row text-center">
                            <div class="col-2 fw-bold">작성자</div>
                            <div class="col-4">{{post.author}}</div>
                            <div class="col-2 fw-bold">조회수</div>
                            <div class="col-4">{{post.hits}}</div>
                        </div> 
                    </li>
                    <li class="list-group-item">
                        <div class="row text-center">
                            <div class="col-6 fw-bold">작성일</div>
                            <div class="col-6">{{post.created_at}}</div>
                        </div> 
                    </li>
                    <li class="list-group-item">
                        <div class="row text-center">
                            <div class="col-6 fw-bold">최종수정일</div>
                            <div class="col-6">{{post.updated_at}}</div>
                        </div> 
                    </li>
                    <li class="list-group-item bg-warning" style="--bs-bg-opacity: .1;">
                        <div class="row text-center" >
                            <div class="col-12 fw-bold">내용</div>
                        </div> 
                    </li>
                </ul>
                {% if post.image %}
                <img src="{{ post.image.url }}" class="card-img my-2" alt="..."> 
                {% endif %}
                <pre class="card-text">{{post.content}}</pre>
            </div>
        </div>
        <br>
        <section id="commentSection">
            <h3>댓글</h3>
            <form action="{% url 'blog:cm-write' post_id=post.pk %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-9">{{ comment_form.content }}</div>
                    <div class="col-3">
                        <input type="submit" class="btn btn-secondary" value="댓글작성">
                    </div>
            </div>
            </form>
            <hr>
            <ul class="list-group list-group-flush">
            {% for comment in comments %}
                <li class="list-group-item bg-success" id="comment_{{forloop.counter}}" style="--bs-bg-opacity: .1;">
                    <div class="row">
                        <div class="col-8">
                            {{comment.author}}
                            {{comment.content}}
                            {{comment.created_at}}
                        </div>
                        <div class="col-4">
                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                {% if user == comment.author or user.is_superuser or user == post.author %}
                                <form action="{% url 'blog:cm-delete' cm_id=comment.pk %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" class="btn btn-outline-danger" value="X">
                                </form>
                                {% endif %}
                                {% if user.is_authenticated %}
                                <button class="btn btn-outline-secondary recm">대댓글</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% with recomments=comment.recomment_set.all %}
                    {% for recomment in recomments %}
                    <div class="row bg-success py-1 border-bottom" style="--bs-bg-opacity: .2;">
                        <div class="col-1">re:</div>
                        <div class="col-2">{{ recomment.author }}</div>
                        <div class="col-5">
                            {{ recomment.content }}
                            {{ recomment.created_at }}
                        </div>
                        <div class="col-4">
                            {% if user == recomment.author or user.is_superuser or user == post.author%}
                            <form action="{% url 'blog:rcm-delete' post_id=post.pk rcm_id=recomment.pk %}" method="post">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-outline-danger" value="X">
                            </form>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                    {% endwith%}
                    <div class="row p-2 hidden">
                        <form action="{% url 'blog:rcm-write' post_id=post.pk cm_id=comment.pk %}" method="post">
                            {% csrf_token %}
                            <div class="row ">
                                <div class="col-2">
                                    <span class="">대댓글</span>
                                </div>
                                <div class="col-8">{{ recomment_form.content }}</div>
                                <div class="col-2"><input type="submit" class="btn btn-outline-danger" value="작성!"></div>
                            </div>
                        </form>
                    </div>
                </li>
            {% endfor %}
            </ul>
        </section>
    </main>
    
    <script>
        const recm_btn_list = document.querySelectorAll(".recm");
        for(btn of recm_btn_list){
            btn.addEventListener("click", (e)=>{
                const $comment = e.target.parentNode.parentNode.parentNode.parentNode;

                let tmp = $comment.childNodes 
                let a = tmp[tmp.length-2]
                a.classList.toggle("hidden");
            })
        };
    
    </script>

    {% comment %}
    <script>
        const recm_btn_list2 = document.querySelectorAll(".recm");
        for(btn of recm_btn_list){
            btn.addEventListener("click", (e)=>{
                let textHTML = `<form action="{% url 'blog:rcm-write' post_id=post.pk cm_id=comment.pk %}" method="post">
                    
                    {% csrf_token %}
                    {{ recomment_form.as_p }}
                    <input type="submit" class="btn btn-outline-danger" value="작성!">
                </form>`;
                const $comment = e.target.parentNode.parentNode.parentNode.parentNode;
                console.log($comment);

                let tempnode = document.createElement('div');
                tempnode.classList.add("row");
                tempnode.innerHTML=textHTML;
                $comment.append(tempnode);
            })
        };
    
    </script>
    {% endcomment %}

    {% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}
<main class="container">
    <h1 class="my-3"> 게시글 수정 </h1>
    <form action="{% url 'blog:edit' post_id=post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row py-2 my-2 border-top border-2">
            <div class="col-2 text-center">제목</div>
            <div class="col-10">{{form.title}}</div>
        </div>
        <div class="row py-2 my-2 border-bottom border-top">
            <div class="col-2 text-center">카테고리</div>
            <div class="col-10">{{form.category}}</div>
        </div>
        <div class="row py-2 my-2 border-bottom">
            <div class="col-2 text-center">내용</div>
            <div class="col-10 text-center">{{form.content}}</div>
        </div>
        <div class="row py-2 my-2 border-bottom border-2">
            <div class="col-2 text-center">현재 이미지</div>
            <div class="col-2">
                <label for="imgdelete">취소</label>
                <input type="checkbox" id="imgdelete" name="cancel" unchecked value="1">
            </div>
            <div class="col-8">{{post.image}}</div>
        </div>
        <div class="row py-2 my-2 border-bottom border-2">
            <div class="col-2 text-center">새 이미지</div>
            <div class="col-10">{{form.image}}</div>
            <input type="hidden" name="originimage" value="{{ post.image }}">
        </div>
        <div class="d-grid gap-2 col-6 mx-auto mt-3">
            <input type="submit" class="btn btn-success mx-auto" value="작성완료">
        </div>
    </form>
</main>
{% comment %}
    <h1> 게시글 작성 </h1>
    <form action="{% url 'blog:edit' post_id=post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}


        <div>
            {{ form.title.label }}
            {{ form.title }}
        </div>
        <div>
            {{ form.content.label }}
            {{ form.content }}
        </div>
        <div>
            {{ form.category.label }}
            {{ form.category }}
        </div>
        <input type="submit" class="btn btn-success">
    </form>
{% endcomment %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
    <main class="container">
        <div class="row my-3">
            <div class="col-md-8 col-lg-9">
                <h2>블로그 포스트 게시판</h2>
                {% if user.is_authenticated %}
                <a href="{% url 'blog:write' %}" class="btn btn-primary">글작성하기</a>
                {% endif %}
                <br>
                {% if searchtag %}
                    <p>"{{searchtag}}" 카테고리</p>
                {% endif %}
                {% if qp %}
                    <p>"{{qp}}" 검색어 결과</p>
                {% endif %}
                {% if posts %}
                <table class="table">
                    <thead class="table-light">
                        <th>글인덱스</th>
                        <th>작성자</th>
                        <th>제목</th>
                        <th>카테고리</th>
                        <th>작성일</th>
                        <th>조회수</th>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                        <tr>
                            <td>{{post.pk}}</td>
                            <td>{{post.author}}</td>
                            <td><a href="{% url 'blog:detail' post_id=post.id %}" class="">{{post.title}}</a></td>
                            <td>{{post.category.name}}</td>
                            <td>{{post.created_at}}</td>
                            <td>{{post.hits}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                    <div>등록된 게시물이 없습니다.</div>
                {% endif %}

                <div class="text-center" id="pagenator">
                    {% if posts.has_previous %}
                        <a href="?page=1" class="otherpage">처음으로</a>
                    {% endif %}
                    {% for page in paginator.page_range %}
                        {% if page == posts.number %}
                            <a href="?search={{qp}}&page={{posts.number}}" class="nowpage">현재</a>
                        {% else %}
                            <a href="?search={{qp}}&page={{page}}" class="otherpage">{{page}}</a>
                        {% endif %}
                        
                    {% endfor %}
                    {% if posts.has_next %}
                        <a href="?search={{qp}}&page={{paginator.num_pages}}" type="button" class="otherpage">끝으로</a>
                    {% endif %}
                </div>

                {% comment %}
                <p>카테고리검색</p>
                <form action="{% url 'blog:search-query' %}" method="get">
                    {%csrf_token%}
                    <input type="text" id="kw" name="cat">
                    <input type="submit" value="검색">
                </form>
                {% endcomment %}
            </div>

            <!-- Categories -->
            <div class="col-md-4 col-lg-3">
                <div class="card mb-4" id="categories-card">
                    <div class="card-header">Categories</div>
                    <div class="card-body d-flex flex-wrap gap-1">
                        {% for category in categories %}
                            <a href="{{ category.get_absolute_url }}?page=1" class="badge rounded-pill bg-info text-dark text-decoration-none">{{ category.name }} ({{ category.post_set.count }})</a>
                        {% endfor %}
                        {% with cat="None" %}
                        <a href="{% url 'blog:search-category' cat=cat%}" class="badge rounded-pill bg-info text-dark text-decoration-none">Uncategory({{ cat_null_posts.count }})</a>
                        {% endwith %}
                        <a href="{% url 'blog:list' %}" class="badge rounded-pill bg-info text-dark text-decoration-none">All ({{ posts_num }})</a>
                    </div>
                </div>
                <!-- Search -->
                <div class="card mb-4" id="search-card">
                    <div class="card-header">Search</div>
                    <div class="card-body">
                        <form action="{% url 'blog:post-search' %}" method="get">
                            <input type="text" class="form-control" name="search">
                            <input type="submit" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
            
        </div>
    </main>

{% endblock %}

blog/templates/blog/post_search.html
<!DOCTYPE html>
<html lang="ko-KR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <h1>블로그 포스트 보여주는 화면입니다</h1>
    <a href="{% url 'blog:write' %}">글작성하기</a>
    <br>
    <hr>
    {% if posts %}
        {% for post in posts %}
            {{ post }}
            <a href="{% url 'blog:detail' post_id=post.id %}">게시물상세보기</a>
            <hr>
        {% endfor %}
    {% else %}
        <div>등록된 게시물이 없습니다.</div>
    {% endif %}
    <p>카테고리검색</p>
    <form action="{% url 'blog:search-query' %}" method="get">
        {%csrf_token%}
        <input type="text" id="kw" name="cat">
        <input type="submit" value="검색">
    </form>

</body>
<script>

</script>
</html>

blog/templates/blog/post_write.html
{% extends 'base.html' %}

{% block content %}

    <main class="container">
        <h1 class="my-3"> 게시글 작성 </h1>
        <form action="{% url 'blog:write' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row py-2 my-2 border-top border-2">
                <div class="col-2 text-center">제목</div>
                <div class="col-10">{{form.title}}</div>
            </div>
            <div class="row py-2 my-2 border-bottom border-top">
                <div class="col-2 text-center">카테고리</div>
                <div class="col-10">{{form.category}}</div>
            </div>
            <div class="row py-2 my-2 border-bottom">
                <div class="col-2 text-center">내용</div>
                <div class="col-10 text-center">{{form.content}}</div>
            </div>
            <div class="row py-2 my-2 border-bottom border-2">
                <div class="col-2 text-center">이미지</div>
                <div class="col-10">{{form.image}}</div>
            </div>
            <div class="d-grid gap-2 col-6 mx-auto mt-3">
                <input type="submit" class="btn btn-success mx-auto" value="작성완료">
            </div>
            
        </form>
    </main>
   
{% endblock %}