blog/urls.py
from django.contrib import admin
from django.urls import path


from . import views

app_name = "blog"

urlpatterns = [
    # 전체 게시물 확인
    path("", views.PostList.as_view(), name="list"),
    # 상세 페이지 조회
    path("<int:post_id>/", views.PostDetail.as_view(), name="detail"),
    # 게시글 작성
    path("create/", views.PostWrite.as_view(), name="write"),
    # 게시글 수정
    path("edit/<int:post_id>/", views.PostEdit.as_view(), name="edit"),
    # 게시글 삭제
    path("delete/<int:post_id>/", views.PostDelete.as_view(), name="delete"),
    # 게시글 검색1
    # path("search/", views.PostSearchQuery.as_view(), name="search-query"),
    # 게시글 검색
    path("posts/", views.PostSearch.as_view(), name="post-search"),
    # 카테고리 종류로 검색
    path("category/<str:cat>/", views.CategorySearch.as_view(), name="search-category"),
    # 코멘트 작성
    path("detail/<int:post_id>/comment/write/", views.CommentWrite.as_view(), name="cm-write"),
    # 코멘트 삭제
    path("detail/comment/<int:cm_id>/delete/", views.CommentDelete.as_view(), name="cm-delete"),
    ## 대댓글 작성
    path("detail/<int:post_id>/comment/<int:cm_id>/replywrite/", views.ReCommentWrite.as_view(), name="rcm-write"),
    ## 대댓글 삭제
    path("detail/<int:post_id>/comment/replydelete/<int:rcm_id>/", views.ReCommentDelete.as_view(), name="rcm-delete"),
    
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexMain.as_view()),
    path("blog/", include("blog.urls")),
    path("user/", include("user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.page_not_found'

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    # 회원가입
    path("register/", views.Register.as_view(), name="register"),
    # 로그인요청
    path("login/", views.Login.as_view(), name="login"),
    # 로그아웃요청
    path("logout/", views.Logout.as_view(), name="logout"),
    # 마이페이지
    path("mypage/", views.MyPage.as_view(), name="mypage"),
    # 프로필 생성, 수정
    path("profile/create/", views.EditProfile.as_view(), name='pf-edit'),
    # 회원 비밀번호 수정
    path("password/change/", views.ChangUserPassword.as_view(), name='pw-edit'),
    
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager # django의 인증기능이 적용된 모델
from django.utils import timezone


class UserManager(BaseUserManager):
    def _create_user(self, username, password, email, is_staff, is_superuser, **extra_fields):
        if not username:
            raise ValueError('User must have an username')
        now = timezone.now() # 현재시간 -> UTC
        # now = timezone.localtime() # 현재 위치 시간으로 기록됨
        email = self.normalize_email(email)
        user = self.model(
            username = username,
            email = email,
            is_staff = is_staff,
            is_active = True,
            is_superuser = is_superuser,
            last_login = now,
            date_joined = now
        )
        user.set_password(password)
        user.save(using = self._db)
        return user
        
    # BaseUserManger함수 1 : create_user
    def create_user(self, username, password, email, **extra_fields):
        return self._create_user(username, password, email, False, False, **extra_fields)
    
    # BaseUserManger함수 2 : create_superuser
    def create_superuser(self, username, password, email, **extra_fields):
        return self._create_user(username, password, email, True, True, **extra_fields)

    
class User(AbstractUser):
    # 한 테이블에 unique는 1개만 있을 수 있습니다.
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(unique=True, max_length=255)
    
    # null과 blank 허용
    name = models.CharField(max_length=50, null=True, blank=True)

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    last_login = models.DateField(null=True, blank=True)
    date_joined = models.DateField(auto_now_add=True)
    
    objects = UserManager()


class Profile(models.Model):
    user = models.OneToOneField('User', on_delete=models.CASCADE, primary_key=True)
    nickname = models.TextField(max_length=50, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    profile_image = models.ImageField(upload_to="profileimages/", null=True, blank=True)

user/forms.py
# user를 auth를 사용해서 개발했으니 폼도 auth에서 제공하는 form을 사용해야 합니다.
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model  
from .models import Profile

from datetime import date

User = get_user_model()


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        fields = ['username', 'email', 'password1', 'password2']
        for f in fields:
            self.fields[f].widget.attrs.update({'class':'form-control'})
            
    class Meta():
        model = User
        fields = ['username', 'email']


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        fields = ['username', 'password']
        for f in fields:
            self.fields[f].widget.attrs.update({'class':'form-control'})
        
    class Meta():
        model = User
        fields = ['username', 'password']
        ## 위젯 적용이 안됨.. 왜지?
        ## Authentication Form에서 미리 지정해버리기 때문에
        ## 생성자를 오버라이드함
        widgets = {
            'username': forms.TextInput(
                attrs={
                    "class": "form-control",
                    'placeholder': '아이디'
                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '비밀번호'
                }
            )
        }
        # widget = {
        #     'email': forms.EmailField(attrs={'placeholder':'email'}),
        #     'password': forms.PasswordInput(attrs={'placeholder':'password'})
        # }


class DateInput(forms.DateInput):
    input_type='date'


class ProfileForm(forms.ModelForm):
    class Meta():
        model = Profile
        fields = ['user', 'nickname', 'birthday', 'profile_image']
        widgets = {
            'nickname': forms.TextInput(
                attrs={
                    "class": "form-control",
                    # 'placeholder': '별명 50자'
                }
            ),
            'birthday': DateInput(
                attrs={
                    'class': 'form-control',
                    # 'placeholder': '생년월일'
                }
            ),
            'profile_image': forms.FileInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }


class UserPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].label = '기존 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False,
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })
    
    # class Meta():
    #     fields = ['old_password', 'new_password1', 'new_password2'] 

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages

from .forms import LoginForm, RegisterForm, ProfileForm, UserPasswordChangeForm
from .models import Profile

class Register(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        form = RegisterForm()
        context = {
            'form': form,
        }
        return render(request, 'user/user_register.html', context=context)
    
    def post(self, request):
        form = RegisterForm(request.POST)
        print(form)
        if form.is_valid():
            user = form.save()
            return redirect("user:login")
        
        form.add_error(None, '폼이 유효하지 않습니다.')
        context = {
            'form': form,
        }
        return render(request, 'user_register.html', context=context)


class Login(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        # togo = None
        
        # if "next" in request.GET.keys() :
        #     togo = "/"+"/".join(request.GET["next"].split("/")[1:4])
            
        form = LoginForm()
        context = {
            'form':form,
            # 'togo': togo
        }
        return render(request, 'user/user_login.html', context=context)
        
    def post(self, request):
        if request.user.is_authenticated:
            return redirect('blog:list')
        
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            passsword = form.cleaned_data['password']
            
            user = authenticate(username = username, password=passsword)
            if user:
                login(request, user)
                
                return redirect('blog:list')
        
        form.add_error(None, '아이디가 없습니다.')
        context = {
            'form':form
        }

        return render(request, 'user/user_login.html', context=context)
        # return redirect('blog:list')


class Logout(View):
    def get(self, request):
        if request.user.is_authenticated:
            print('Bye~')
            logout(request)
        
        return redirect('/')


class MyPage(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        my_posts = user.post_set.all()
        print(my_posts)
        profile_form = ProfileForm()
        profile = None
        
        if hasattr(user, "profile"):
            profile = user.profile
            profile_form = ProfileForm(initial={
                'user': profile.user,
                'nickname': profile.nickname, 
                'birthday': profile.birthday,
                'profile_image': profile.profile_image
            })
            
        context = {
            'user': user,
            'profile_form': profile_form,
            'profile': profile,
            'my_posts': my_posts,
        }
        return render(request, 'user/user_mypage.html', context=context)


class EditProfile(LoginRequiredMixin, View):
    def post(self, request):
        nickname = request.POST['nickname']
        birthday = request.POST['birthday']
        print(request.POST['birthday'])
            
        if request.POST["type"] == "create":
            profile_image = None
            if hasattr(request.FILES, 'profile_image'):
                profile_image = request.FILES['profile_image']
            Profile(user=request.user, nickname=nickname, birthday=birthday, profile_image=profile_image).save()
        else:
            profile = get_object_or_404(Profile, user=request.user)
            profile.nickname = request.POST['nickname']
            profile.birthday = request.POST['birthday']
            if hasattr(request.FILES,'profile_image'):
                profile.profile_image= request.FILES['profile_image']
            
            profile.save()
            
        return redirect('user:mypage')


# django.contrib.auth.views.PasswordChangeView 를 이용해서 간단히 개발할 수 있습니다.
class ChangUserPassword(LoginRequiredMixin, View):
    def get(self, request):
        form = UserPasswordChangeForm(request.user)
        context ={
            'form': form,
        }
        return render(request, 'user/user_pwedit.html', context)
        
    def post(self, request):
        form = UserPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.user = request.user
            user = form.save()
            update_session_auth_hash(request, user)  # 비밀번호 변경 후에도 변경된 비밀번호로 로그인 세션 유지해줌
            messages.success(request, 'Your password was successfully updated!')
            return redirect('user:mypage')
        else:
            messages.error(request, 'Please correct the error below.')
        
        context = {
            'form':form,
        }
        return render(request, 'user/user_pwedit.html', context=context)

user/templates/user/user_login.html
{% extends 'base.html' %}

{% block content %}

<main class="container" style="height:65vh;">
    <div class="row justify-content-center py-5">
        <div class="col-8 text-center">
            <h1>로그인</h1>
        </div>
    </div>
    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        <div class="d-grid gap-2 col-6 mx-auto">
            <div class="row mb-3 justify-content-center">
                <div class="col-3">아이디</div>
                <div class="col-9">{{ form.username }}</div>
            </div>
            <div class="row mb-3 justify-content-center">
                <div class="col-3">비밀번호</div>
                <div class="col-9">{{ form.password }}</div>
            </div>
            <input type="hidden" name="next" value="{{ togo }}" >
            {%if form.errors %}
            <div class="alert alert-danger">
                {% for field in form %}
                    <!-- 필드 오류 -->
                    {% if field.errors %}
                    <div>
                        <strong>Field Error: </strong>{{ field.label }} - {{ field.errors }}
                    </div>
                    {% endif %}
                {% endfor %}
                <!-- 넌필드 오류 -->
                {% for error in form.non_field_errors %}
                <div>
                    <strong>Nonfield Error:</strong>{{ error }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <input type="submit" value="로그인" class="btn btn-lg btn-primary btn-block">
        </div>
    </form>
</main>

{% endblock %}

user/templates/user/user_mypage.html
{% extends 'base.html' %}

{% block content %}

<main class="container">
    <h1 class="my-3">마이 페이지</h1>
    <h3 class="my-2">안녕하세요 {{user.username}} 님!</h3>
    
    <div class="d-grid gap-2 mx-auto">
        <div class="row"><h4>회원정보</h4></div>
        <div class="row">
            <div>회원 아이디 : {{user.username}}</div>
        </div>
        <div class="row">
            <div>회원 이메일 : {{user.email}}</div>
        </div>
        <div class="row justify-content-center ">
            <div class="col-4 d-grid">
                <button class="btn btn-success" id="userchangebtn" data-bs-toggle="modal" data-bs-target="#userModal">회원정보 확인</button>
            </div>
            <div class="col-4 d-grid">
                <a href="{% url 'user:pw-edit' %}" class="btn btn-success">비밀번호 변경</a>
            </div>
            <div class="col-4 d-grid">
                <button class="btn btn-success" id="userpostsbtn" data-bs-toggle="modal" data-bs-target="#userPostsModal">내 작성글</button>
            </div>
        </div>
    </div>

    <h2 class="mt-4">내 프로필</h2>

    
    <section class="card">
        <div class="card-header">my profile</div>
        {% if user.profile %}
        <div class="card-body">
            <div>별명 : {{profile.nickname}}</div>
            <div>생일 : {{profile.birthday|date:'Y-m-d'}}</div>
            <div>프로필 사진 : </div>
            <img src="{{user.profile.profile_image.url}}" class="card-img my-2" style="width:200px; height:200px;">
        </div>
        {% else %}
        <div class="row justify-content-center">프로필이 없습니다.</div>
        {% endif %}
        <div class="row justify-content-center">
            <div class="d-grid gap-2 col-6 mx-auto"></div>
        </div>
    </section c>
    

    <div class="row justify-content-center my-3">
        <div class="d-grid col-4">
            {% if not user.profile %}
            <button class="btn btn-success" id="profilebtn" data-bs-toggle="modal" data-bs-target="#profileModal">프로필 생성</button>
            {% else %}
            <button class="btn btn-success" id="profilebtn" data-bs-toggle="modal" data-bs-target="#profileModal">프로필 수정</button>
            {% endif %}
        </div>
    </div>

    

</main>

<!-- User Edit modal -->
<div class="modal" id="userModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="userModalTitle">회원정보 수정</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="닫기"></button>
            </div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="modal-body">
                <p>내 정보</p>
                <p>계정 아이디 : {{ user.username }}</p>
                <p>이메일 : {{ user.email }}</p>
            </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- Profile modal -->
<div class="modal" id="profileModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="profileModalTitle">프로필 작성</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
        <form action="{% url 'user:pf-edit' %}" method="post" enctype="multipart/form-data">
        {% if user.profile %}
            <input type="hidden" name="type" value="edit">
        {% else %}
            <input type="hidden" name="type" value="create">
        {% endif %}
            {% csrf_token %}
            <div class="modal-body">
                <p>프로필 정보를 입력해주세요</p>
                <p>계정 : {{ user.username }}</p>
                <p>{{profile.birthday|date:'Y-m-d'}}</p>
                <input type="text" id="nickdummy" value="{{profile.nickname}}" class="form-control">
                {{profile_form.birthday}}
                
                <p>기존 이미지 :{{profile.profile_image}}</p>
                <img src="{{ profile.profile_image.url }}" alt="">
                {{profile_form.nickname}}
                {{profile_form.profile_image}}
            </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="프로필 저장">
                </div>
            </div>
        </form ac>
    </div>
</div>

<!-- User Post modal -->
<div class="modal" id="userPostsModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="userPostsModalTitle">내가 작성한 게시물</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="닫기"></button>
            </div>
            <div class="modal-body">
                {% if my_posts %}
                <table class="table">
                    <thead>
                        <th>글번호</th>
                        <th>제목</th>
                        <th>작성일</th>
                        <th> </th>
                    </thead>
                    <tbody>
                        {% for post in my_posts %}
                        <tr>
                            <td>{{post.id}}</td>
                            <td>{{post.title}}</td>
                            <td>{{post.created_at}}</td>
                            <td><a href="{% url 'blog:detail' post_id=post.id %}" class="btn btn-primary">보기</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                    <p>작성한 게시물이 없습니다.</p>
                {% endif%}
            </div>
        
    </div>
</div>

<script>
    let profModal = document.querySelector('#profileModal');
    let profbtn = document.querySelector('#profilebtn');
    

    profModal.addEventListener("shown.bs.modal", function (e) {
        e.preventDefault();
        });
    
    let userModal = document.querySelector('#userModal');
    let userbtn = document.querySelector('#userchangebtn');

    userModal.addEventListener("shown.bs.modal", function (e) {
        e.preventDefault();
        });
    
    let postsModal = document.querySelector('#userPostsModal');
    let postsbtn = document.querySelector('#userpostsbtn')
    postsModal.addEventListener("shown.bs.modal", function(e) {
        e.preventDefault();
        });


    let nicknamehidden = document.querySelector('#id_nickname')
    nicknamehidden.classList.add('hide')

    let nicknamedummy = document.querySelector('#nickdummy')
    let birthdummy = document.querySelector('#birthdummy')
    let imagedummy = document.querySelector('#imagedummy')

    nicknamedummy.addEventListener('input', (e)=>{
        e.preventDefault();
        nicknamehidden.value = nicknamedummy.value
    })

</script>
{% endblock %}

user/templates/user/user_pwedit.html
{% extends 'base.html' %}

{% block content %}

<main class="container">
    <div class="row justify-content-center py-5">
        <div class="col-8 text-center">
            <h1>비밀번호 변경</h1>
        </div>
    </div>
    <form action="{% url 'user:pw-edit' %}" method="post">
        {% csrf_token %}
        
        <div class="d-grid gap-2 col-6 mx-auto">
            {{ form }}
            {% if form.errors %}
            <div class="alert alert-danger">
            {% for field in form %}
                <!-- 필드 오류 -->
                {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
                {% endif %}
                <!-- 넌필드 오류 -->
                {% for error in form.non_field_errors %}
                <div>
                    <strong>{{ error }}</strong>
                </div>
                {% endfor %}
            {% endfor %}
            </div>
            {% endif %}
            <input type="submit" value="비밀번호 수정" class="btn btn-lg btn-primary btn-block">
            {% comment %}
            <div class="row mb-3 justify-content-center">
                <div class="col-4">이전 비밀번호</div>
                <div class="col-8">{{form.old_password}}</div>
            </div>
            <div class="row mb-3 justify-content-center">
                <div class="col-4">새 비밀번호</div>
                <div class="col-8">{{form.new_password1}}</div>
            </div>
            <div class="row mb-3 justify-content-center">
                <div class="col-4">비밀번호 확인</div>
                <div class="col-8">{{form.new_password2}}</div>
            </div>
            <input type="submit" value="비밀번호 수정" class="btn btn-lg btn-primary btn-block">
            {% endcomment %}
        </div>
    </form>
</main>


{% endblock %}

user/templates/user/user_register.html
{% extends 'base.html' %}

{% block content %}

<main class="container">
    <div class="row justify-content-center py-5">
        <div class="col-8 text-center">
            <h1>회원가입</h1>
        </div>
    </div>
    <form action="{% url 'user:register' %}" method="post">
        {% csrf_token %}
        <div class="d-grid gap-2 col-6 mx-auto">
            <div class="row mb-3 justify-content-center">
                <div class="col-3">아이디</div>
                <div class="col-9">{{ form.username }}</div>
            </div>
            <div class="row mb-3 justify-content-center">
                <div class="col-3">이메일</div>
                <div class="col-9">{{ form.email }}</div>
            </div>
            <div class="row mb-3 justify-content-center">
                <div class="col-3">비밀번호</div>
                <div class="col-9">{{ form.password1 }}</div>
            </div>
            <div class="row mb-3 justify-content-center">
                <div class="col-3">비밀번호확인</div>
                <div class="col-9">{{ form.password2 }}</div>
            </div>
            <input type="hidden" name="next" value="{{ togo }}" >
            <input type="submit" value="회원가입" class="btn btn-lg btn-primary btn-block">
        </div>
    </form>
</main>


{% endblock %}