blog/urls.py
from django.contrib import admin
from django.urls import path


from . import views

app_name = "blog"

urlpatterns = [
    # 전체 게시물 확인
    path("", views.PostList.as_view(), name="list"),
    # 상세 페이지 조회
    path("<int:post_id>/", views.PostDetail.as_view(), name="detail"),
    # 게시글 작성
    path("create/", views.PostWrite.as_view(), name="write"),
    # 게시글 수정
    path("edit/<int:post_id>/", views.PostEdit.as_view(), name="edit"),
    # 게시글 삭제
    path("delete/<int:post_id>/", views.PostDelete.as_view(), name="delete"),
    # 게시글 검색1
    # path("search/", views.PostSearchQuery.as_view(), name="search-query"),
    # 게시글 검색
    path("posts/", views.PostSearch.as_view(), name="post-search"),
    # 카테고리 종류로 검색
    path("category/<str:cat>/", views.CategorySearch.as_view(), name="search-category"),
    # 코멘트 작성
    path("detail/<int:post_id>/comment/write/", views.CommentWrite.as_view(), name="cm-write"),
    # 코멘트 삭제
    path("detail/comment/<int:cm_id>/delete/", views.CommentDelete.as_view(), name="cm-delete"),
    ## 대댓글 작성
    path("detail/<int:post_id>/comment/<int:cm_id>/replywrite/", views.ReCommentWrite.as_view(), name="rcm-write"),
    ## 대댓글 삭제
    path("detail/<int:post_id>/comment/replydelete/<int:rcm_id>/", views.ReCommentDelete.as_view(), name="rcm-delete"),
    
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexMain.as_view()),
    path("blog/", include("blog.urls")),
    path("user/", include("user.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.page_not_found'

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    # 회원가입
    path("register/", views.Register.as_view(), name="register"),
    # 로그인요청
    path("login/", views.Login.as_view(), name="login"),
    # 로그아웃요청
    path("logout/", views.Logout.as_view(), name="logout"),
    # 마이페이지
    path("mypage/", views.MyPage.as_view(), name="mypage"),
    # 프로필 생성, 수정
    path("profile/create/", views.EditProfile.as_view(), name='pf-edit'),
    # 회원 비밀번호 수정
    path("password/change/", views.ChangUserPassword.as_view(), name='pw-edit'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko-KR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="..\..\static\css\profilestyle.css">
    <link rel="stylesheet" href="..\..\static\css\common.css">
    <!-- <link rel="stylesheet" href="..\..\static\css\login-join.css"> -->
    <title></title>
    <style>
        .hidden {
            display: none;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        <div class="row my-3 justify-content-center">
            <div class="col-md-10 col-lg-11" id="main-area">
                <!--                post detail 과 list가 메인영역 제외하고
                동일한 디자인으로 할 것이므로 메인영역만 빼고 base.html로 모듈화 한 것-->
                {% block content %}
                {% endblock %}
            </div>
        </div>
    
    </div>


    

    {% include 'footer.html' %}

    {% block script %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<!-- Footer-->
<footer class="mt-5 py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; JS's Blog</p>
    </div>
  </footer>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <main class="container" style="height:65vh;">
        <div class="row justify-content-center py-5">
            <div class="col-8 text-center">
                <h1>블로그에 온 것을 환영합니다!</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="d-grid gap-2 col-6 mx-auto">
                <a href="{% url 'blog:list' %}?page=1" class="btn btn-success">게시판 보기</a>
                {% if user.is_authenticated %}
                <a href="{% url 'user:logout' %}" class="btn btn-success">로그아웃</a>
                <a href="{% url 'user:mypage' %}" class="btn btn-success">마이페이지</a>
                {% else %}
                <a href="{% url 'user:login' %}" class="btn btn-success">로그인</a>
                <a href="{% url 'user:register' %}" class="btn btn-success">회원가입</a>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark bg-gradient" style="--bs-bg-opacity: .3;">
    <div class="container">
        <a class="navbar-brand" href="/">JS의 블로그</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:list' %}">Blog</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:logout' %}" data-toggle="modal" data-target="#loginModal"><span>Log Out</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'user:mypage' %}">반갑습니다 <span class="text-primary fs-6 text">{{user.username}}</span> 님!</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:login' %}" data-toggle="modal" data-target="#loginModal">Log In</a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user:register' %}" data-toggle="modal" data-target="#loginModal">Sign In</a>
                </li>
                {% endif %}
        </div>
    </div>
</nav>